version: 1
accounts:
  - name: dymemaster1
    coins: ["200000000000000DYME", "2000000000000stake"]
  - name: dymemaster2
    coins: ["200000000000000DYME", "2000000000000stake"]
genesis:
  chain_id: dymechain
validators:
  - name: dymemaster1
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: dymemaster2
  coins: ["200000000DYME", "100000stake"]
  host: 0.0.0.0:4500
