{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # This is a TOML config file.\
# For more information, see https://github.com/toml-lang/toml\
\
###############################################################################\
###                           Client Configuration                            ###\
###############################################################################\
\
# The network chain ID\
chain-id = "dymechain"\
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)\
keyring-backend = "test"\
# CLI output format (text|json)\
output = "text"\
# <host>:<port> to Tendermint RPC interface for this chain\
node = "tcp://localhost:26657"\
# Transaction broadcasting mode (sync|async|block)\
broadcast-mode = "block"}