// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymechain/dymegovernance/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e88a94e2c2c6a2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e88a94e2c2c6a2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetKeyValueRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *QueryGetKeyValueRequest) Reset()         { *m = QueryGetKeyValueRequest{} }
func (m *QueryGetKeyValueRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetKeyValueRequest) ProtoMessage()    {}
func (*QueryGetKeyValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e88a94e2c2c6a2, []int{2}
}
func (m *QueryGetKeyValueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKeyValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKeyValueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKeyValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKeyValueRequest.Merge(m, src)
}
func (m *QueryGetKeyValueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKeyValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKeyValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKeyValueRequest proto.InternalMessageInfo

func (m *QueryGetKeyValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type QueryGetKeyValueResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *QueryGetKeyValueResponse) Reset()         { *m = QueryGetKeyValueResponse{} }
func (m *QueryGetKeyValueResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetKeyValueResponse) ProtoMessage()    {}
func (*QueryGetKeyValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e88a94e2c2c6a2, []int{3}
}
func (m *QueryGetKeyValueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKeyValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKeyValueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKeyValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKeyValueResponse.Merge(m, src)
}
func (m *QueryGetKeyValueResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKeyValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKeyValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKeyValueResponse proto.InternalMessageInfo

func (m *QueryGetKeyValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type QueryGetAdvisorsRequest struct {
	Advisorparam1 string `protobuf:"bytes,1,opt,name=advisorparam1,proto3" json:"advisorparam1,omitempty"`
	Advisorparam2 string `protobuf:"bytes,2,opt,name=advisorparam2,proto3" json:"advisorparam2,omitempty"`
}

func (m *QueryGetAdvisorsRequest) Reset()         { *m = QueryGetAdvisorsRequest{} }
func (m *QueryGetAdvisorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAdvisorsRequest) ProtoMessage()    {}
func (*QueryGetAdvisorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e88a94e2c2c6a2, []int{4}
}
func (m *QueryGetAdvisorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAdvisorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAdvisorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAdvisorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAdvisorsRequest.Merge(m, src)
}
func (m *QueryGetAdvisorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAdvisorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAdvisorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAdvisorsRequest proto.InternalMessageInfo

func (m *QueryGetAdvisorsRequest) GetAdvisorparam1() string {
	if m != nil {
		return m.Advisorparam1
	}
	return ""
}

func (m *QueryGetAdvisorsRequest) GetAdvisorparam2() string {
	if m != nil {
		return m.Advisorparam2
	}
	return ""
}

type QueryGetAdvisorsResponse struct {
	Advisordata string `protobuf:"bytes,1,opt,name=advisordata,proto3" json:"advisordata,omitempty"`
}

func (m *QueryGetAdvisorsResponse) Reset()         { *m = QueryGetAdvisorsResponse{} }
func (m *QueryGetAdvisorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAdvisorsResponse) ProtoMessage()    {}
func (*QueryGetAdvisorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29e88a94e2c2c6a2, []int{5}
}
func (m *QueryGetAdvisorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAdvisorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAdvisorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAdvisorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAdvisorsResponse.Merge(m, src)
}
func (m *QueryGetAdvisorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAdvisorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAdvisorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAdvisorsResponse proto.InternalMessageInfo

func (m *QueryGetAdvisorsResponse) GetAdvisordata() string {
	if m != nil {
		return m.Advisordata
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "dymechain.dymegovernance.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "dymechain.dymegovernance.QueryParamsResponse")
	proto.RegisterType((*QueryGetKeyValueRequest)(nil), "dymechain.dymegovernance.QueryGetKeyValueRequest")
	proto.RegisterType((*QueryGetKeyValueResponse)(nil), "dymechain.dymegovernance.QueryGetKeyValueResponse")
	proto.RegisterType((*QueryGetAdvisorsRequest)(nil), "dymechain.dymegovernance.QueryGetAdvisorsRequest")
	proto.RegisterType((*QueryGetAdvisorsResponse)(nil), "dymechain.dymegovernance.QueryGetAdvisorsResponse")
}

func init() {
	proto.RegisterFile("dymechain/dymegovernance/query.proto", fileDescriptor_29e88a94e2c2c6a2)
}

var fileDescriptor_29e88a94e2c2c6a2 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x8a, 0xd3, 0x40,
	0x18, 0xc7, 0x9b, 0x75, 0xb7, 0xe0, 0x14, 0x41, 0xc6, 0x82, 0xa5, 0x48, 0x0c, 0xc3, 0x0a, 0x8b,
	0xba, 0x1d, 0x13, 0xf1, 0x22, 0x22, 0xb8, 0x07, 0x15, 0x04, 0xd1, 0x82, 0x1e, 0xbc, 0x2c, 0xd3,
	0xf6, 0x23, 0x86, 0x6e, 0x67, 0xb2, 0x99, 0x69, 0x30, 0x2c, 0xbd, 0xf8, 0x00, 0x2a, 0xf8, 0x18,
	0xbe, 0x86, 0x87, 0x3d, 0x2e, 0x78, 0xf1, 0x24, 0xd2, 0xfa, 0x20, 0x92, 0x99, 0x59, 0xb3, 0x49,
	0x88, 0xdb, 0xbd, 0xcd, 0x7c, 0xf9, 0x7f, 0xdf, 0xff, 0x37, 0xf3, 0x9f, 0xa0, 0xed, 0x49, 0x36,
	0x83, 0xf1, 0x7b, 0x16, 0x71, 0x9a, 0xaf, 0x42, 0x91, 0x42, 0xc2, 0x19, 0x1f, 0x03, 0x3d, 0x9c,
	0x43, 0x92, 0x0d, 0xe2, 0x44, 0x28, 0x81, 0x7b, 0xff, 0x54, 0x83, 0xb2, 0xaa, 0xdf, 0x0d, 0x45,
	0x28, 0xb4, 0x88, 0xe6, 0x2b, 0xa3, 0xef, 0xdf, 0x08, 0x85, 0x08, 0x0f, 0x80, 0xb2, 0x38, 0xa2,
	0x8c, 0x73, 0xa1, 0x98, 0x8a, 0x04, 0x97, 0xf6, 0xeb, 0xed, 0xb1, 0x90, 0x33, 0x21, 0xe9, 0x88,
	0x49, 0x6b, 0x43, 0x53, 0x7f, 0x04, 0x8a, 0xf9, 0x34, 0x66, 0x61, 0xc4, 0xb5, 0xd8, 0x6a, 0x6f,
	0x35, 0xf2, 0xc5, 0x2c, 0x61, 0x33, 0x3b, 0x92, 0x74, 0x11, 0x7e, 0x9d, 0x0f, 0x7a, 0xa5, 0x8b,
	0x43, 0x38, 0x9c, 0x83, 0x54, 0xe4, 0x0d, 0xba, 0x56, 0xaa, 0xca, 0x58, 0x70, 0x09, 0xf8, 0x31,
	0x6a, 0x9b, 0xe6, 0x9e, 0xe3, 0x39, 0x3b, 0x9d, 0xc0, 0x1b, 0x34, 0x1d, 0x6f, 0x60, 0x3a, 0xf7,
	0x36, 0x8f, 0x7f, 0xdd, 0x6c, 0x0d, 0x6d, 0x17, 0xb9, 0x83, 0xae, 0xeb, 0xb1, 0xcf, 0x40, 0xbd,
	0x80, 0xec, 0x2d, 0x3b, 0x98, 0x83, 0x75, 0xc4, 0x57, 0xd1, 0xa5, 0x29, 0x64, 0x7a, 0xee, 0xe5,
	0x61, 0xbe, 0x24, 0xf7, 0x50, 0xaf, 0x2e, 0xb6, 0x20, 0x5d, 0xb4, 0x95, 0xe6, 0x05, 0xab, 0x37,
	0x1b, 0x02, 0xc5, 0xf8, 0x27, 0x93, 0x34, 0x92, 0x22, 0x39, 0x3d, 0x10, 0xde, 0x46, 0x57, 0x98,
	0x29, 0x69, 0x14, 0xdf, 0x36, 0x96, 0x8b, 0x55, 0x55, 0xd0, 0xdb, 0xa8, 0xab, 0x02, 0xf2, 0xa8,
	0x00, 0x2b, 0x6c, 0x2c, 0x98, 0x87, 0x3a, 0x56, 0x3c, 0x61, 0x8a, 0x59, 0x97, 0xb3, 0xa5, 0xe0,
	0xd3, 0x26, 0xda, 0xd2, 0xed, 0xf8, 0xb3, 0x83, 0xda, 0xe6, 0x9a, 0xf0, 0xdd, 0xe6, 0x8b, 0xac,
	0xa7, 0xd3, 0xdf, 0x5d, 0x53, 0x6d, 0x98, 0xc8, 0xce, 0xc7, 0x1f, 0x7f, 0xbe, 0x6e, 0x10, 0xec,
	0xd1, 0x73, 0x9e, 0x04, 0xfe, 0xe6, 0xa0, 0xce, 0x99, 0xeb, 0xc6, 0xfe, 0x39, 0x46, 0xf5, 0x1c,
	0xfb, 0xc1, 0x45, 0x5a, 0x2c, 0xe0, 0x03, 0x0d, 0x48, 0xf1, 0x6e, 0x33, 0x60, 0x08, 0x6a, 0x7f,
	0x0a, 0xd9, 0xbe, 0x0e, 0x9a, 0x1e, 0x4d, 0x21, 0x5b, 0xe0, 0xef, 0x86, 0xf6, 0x34, 0x83, 0x75,
	0x68, 0x2b, 0xcf, 0x62, 0x1d, 0xda, 0x6a, 0xc4, 0xe4, 0xa5, 0xa6, 0x7d, 0x8e, 0x9f, 0xfe, 0x9f,
	0xd6, 0x66, 0x2e, 0xe9, 0x51, 0xe9, 0x8d, 0x2d, 0xca, 0xfb, 0x60, 0xb1, 0xf7, 0xf0, 0x78, 0xe9,
	0x3a, 0x27, 0x4b, 0xd7, 0xf9, 0xbd, 0x74, 0x9d, 0x2f, 0x2b, 0xb7, 0x75, 0xb2, 0x72, 0x5b, 0x3f,
	0x57, 0x6e, 0xeb, 0x9d, 0x57, 0x18, 0x7c, 0xa8, 0x5a, 0xa8, 0x2c, 0x06, 0x39, 0x6a, 0xeb, 0x9f,
	0xf8, 0xfe, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x74, 0x96, 0xe4, 0x8d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetKeyValue items.
	GetKeyValue(ctx context.Context, in *QueryGetKeyValueRequest, opts ...grpc.CallOption) (*QueryGetKeyValueResponse, error)
	// Queries a list of GetAdvisors items.
	GetAdvisors(ctx context.Context, in *QueryGetAdvisorsRequest, opts ...grpc.CallOption) (*QueryGetAdvisorsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetKeyValue(ctx context.Context, in *QueryGetKeyValueRequest, opts ...grpc.CallOption) (*QueryGetKeyValueResponse, error) {
	out := new(QueryGetKeyValueResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Query/GetKeyValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAdvisors(ctx context.Context, in *QueryGetAdvisorsRequest, opts ...grpc.CallOption) (*QueryGetAdvisorsResponse, error) {
	out := new(QueryGetAdvisorsResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Query/GetAdvisors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetKeyValue items.
	GetKeyValue(context.Context, *QueryGetKeyValueRequest) (*QueryGetKeyValueResponse, error)
	// Queries a list of GetAdvisors items.
	GetAdvisors(context.Context, *QueryGetAdvisorsRequest) (*QueryGetAdvisorsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetKeyValue(ctx context.Context, req *QueryGetKeyValueRequest) (*QueryGetKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyValue not implemented")
}
func (*UnimplementedQueryServer) GetAdvisors(ctx context.Context, req *QueryGetAdvisorsRequest) (*QueryGetAdvisorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdvisors not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetKeyValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Query/GetKeyValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetKeyValue(ctx, req.(*QueryGetKeyValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAdvisors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAdvisorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAdvisors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Query/GetAdvisors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAdvisors(ctx, req.(*QueryGetAdvisorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dymechain.dymegovernance.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetKeyValue",
			Handler:    _Query_GetKeyValue_Handler,
		},
		{
			MethodName: "GetAdvisors",
			Handler:    _Query_GetAdvisors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dymechain/dymegovernance/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetKeyValueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKeyValueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKeyValueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKeyValueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKeyValueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKeyValueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAdvisorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAdvisorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAdvisorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Advisorparam2) > 0 {
		i -= len(m.Advisorparam2)
		copy(dAtA[i:], m.Advisorparam2)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Advisorparam2)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Advisorparam1) > 0 {
		i -= len(m.Advisorparam1)
		copy(dAtA[i:], m.Advisorparam1)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Advisorparam1)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAdvisorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAdvisorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAdvisorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Advisordata) > 0 {
		i -= len(m.Advisordata)
		copy(dAtA[i:], m.Advisordata)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Advisordata)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetKeyValueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKeyValueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAdvisorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Advisorparam1)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Advisorparam2)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAdvisorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Advisordata)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKeyValueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKeyValueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKeyValueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKeyValueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKeyValueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKeyValueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAdvisorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAdvisorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAdvisorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advisorparam1", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advisorparam1 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advisorparam2", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advisorparam2 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAdvisorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAdvisorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAdvisorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advisordata", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advisordata = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)