// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymechain/dymegovernance/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetKeyValue struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *MsgSetKeyValue) Reset()         { *m = MsgSetKeyValue{} }
func (m *MsgSetKeyValue) String() string { return proto.CompactTextString(m) }
func (*MsgSetKeyValue) ProtoMessage()    {}
func (*MsgSetKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{0}
}
func (m *MsgSetKeyValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetKeyValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetKeyValue.Merge(m, src)
}
func (m *MsgSetKeyValue) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetKeyValue proto.InternalMessageInfo

func (m *MsgSetKeyValue) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetKeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MsgSetKeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MsgSetKeyValueResponse struct {
}

func (m *MsgSetKeyValueResponse) Reset()         { *m = MsgSetKeyValueResponse{} }
func (m *MsgSetKeyValueResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetKeyValueResponse) ProtoMessage()    {}
func (*MsgSetKeyValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{1}
}
func (m *MsgSetKeyValueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetKeyValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetKeyValueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetKeyValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetKeyValueResponse.Merge(m, src)
}
func (m *MsgSetKeyValueResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetKeyValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetKeyValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetKeyValueResponse proto.InternalMessageInfo

type MsgStakedyme struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgStakedyme) Reset()         { *m = MsgStakedyme{} }
func (m *MsgStakedyme) String() string { return proto.CompactTextString(m) }
func (*MsgStakedyme) ProtoMessage()    {}
func (*MsgStakedyme) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{2}
}
func (m *MsgStakedyme) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStakedyme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStakedyme.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStakedyme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStakedyme.Merge(m, src)
}
func (m *MsgStakedyme) XXX_Size() int {
	return m.Size()
}
func (m *MsgStakedyme) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStakedyme.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStakedyme proto.InternalMessageInfo

func (m *MsgStakedyme) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgStakedymeResponse struct {
}

func (m *MsgStakedymeResponse) Reset()         { *m = MsgStakedymeResponse{} }
func (m *MsgStakedymeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStakedymeResponse) ProtoMessage()    {}
func (*MsgStakedymeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{3}
}
func (m *MsgStakedymeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStakedymeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStakedymeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStakedymeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStakedymeResponse.Merge(m, src)
}
func (m *MsgStakedymeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStakedymeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStakedymeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStakedymeResponse proto.InternalMessageInfo

type MsgElectAdvisor struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgElectAdvisor) Reset()         { *m = MsgElectAdvisor{} }
func (m *MsgElectAdvisor) String() string { return proto.CompactTextString(m) }
func (*MsgElectAdvisor) ProtoMessage()    {}
func (*MsgElectAdvisor) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{4}
}
func (m *MsgElectAdvisor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgElectAdvisor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgElectAdvisor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgElectAdvisor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgElectAdvisor.Merge(m, src)
}
func (m *MsgElectAdvisor) XXX_Size() int {
	return m.Size()
}
func (m *MsgElectAdvisor) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgElectAdvisor.DiscardUnknown(m)
}

var xxx_messageInfo_MsgElectAdvisor proto.InternalMessageInfo

func (m *MsgElectAdvisor) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgElectAdvisorResponse struct {
}

func (m *MsgElectAdvisorResponse) Reset()         { *m = MsgElectAdvisorResponse{} }
func (m *MsgElectAdvisorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgElectAdvisorResponse) ProtoMessage()    {}
func (*MsgElectAdvisorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{5}
}
func (m *MsgElectAdvisorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgElectAdvisorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgElectAdvisorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgElectAdvisorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgElectAdvisorResponse.Merge(m, src)
}
func (m *MsgElectAdvisorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgElectAdvisorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgElectAdvisorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgElectAdvisorResponse proto.InternalMessageInfo

type MsgAdviceOnProposal struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ProposalId      string `protobuf:"bytes,2,opt,name=proposalId,proto3" json:"proposalId,omitempty"`
	AdvisoryOutcome string `protobuf:"bytes,3,opt,name=advisoryOutcome,proto3" json:"advisoryOutcome,omitempty"`
}

func (m *MsgAdviceOnProposal) Reset()         { *m = MsgAdviceOnProposal{} }
func (m *MsgAdviceOnProposal) String() string { return proto.CompactTextString(m) }
func (*MsgAdviceOnProposal) ProtoMessage()    {}
func (*MsgAdviceOnProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{6}
}
func (m *MsgAdviceOnProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAdviceOnProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAdviceOnProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAdviceOnProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAdviceOnProposal.Merge(m, src)
}
func (m *MsgAdviceOnProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgAdviceOnProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAdviceOnProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAdviceOnProposal proto.InternalMessageInfo

func (m *MsgAdviceOnProposal) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAdviceOnProposal) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

func (m *MsgAdviceOnProposal) GetAdvisoryOutcome() string {
	if m != nil {
		return m.AdvisoryOutcome
	}
	return ""
}

type MsgAdviceOnProposalResponse struct {
}

func (m *MsgAdviceOnProposalResponse) Reset()         { *m = MsgAdviceOnProposalResponse{} }
func (m *MsgAdviceOnProposalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAdviceOnProposalResponse) ProtoMessage()    {}
func (*MsgAdviceOnProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_091905762146b04b, []int{7}
}
func (m *MsgAdviceOnProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAdviceOnProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAdviceOnProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAdviceOnProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAdviceOnProposalResponse.Merge(m, src)
}
func (m *MsgAdviceOnProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAdviceOnProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAdviceOnProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAdviceOnProposalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetKeyValue)(nil), "dymechain.dymegovernance.MsgSetKeyValue")
	proto.RegisterType((*MsgSetKeyValueResponse)(nil), "dymechain.dymegovernance.MsgSetKeyValueResponse")
	proto.RegisterType((*MsgStakedyme)(nil), "dymechain.dymegovernance.MsgStakedyme")
	proto.RegisterType((*MsgStakedymeResponse)(nil), "dymechain.dymegovernance.MsgStakedymeResponse")
	proto.RegisterType((*MsgElectAdvisor)(nil), "dymechain.dymegovernance.MsgElectAdvisor")
	proto.RegisterType((*MsgElectAdvisorResponse)(nil), "dymechain.dymegovernance.MsgElectAdvisorResponse")
	proto.RegisterType((*MsgAdviceOnProposal)(nil), "dymechain.dymegovernance.MsgAdviceOnProposal")
	proto.RegisterType((*MsgAdviceOnProposalResponse)(nil), "dymechain.dymegovernance.MsgAdviceOnProposalResponse")
}

func init() { proto.RegisterFile("dymechain/dymegovernance/tx.proto", fileDescriptor_091905762146b04b) }

var fileDescriptor_091905762146b04b = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0xe9, 0x6d, 0xee, 0xbd, 0xe1, 0x5c, 0x72, 0x21, 0x95, 0x60, 0xad, 0xb1, 0xc1, 0x2e,
	0x4c, 0x8d, 0xb1, 0xf8, 0x27, 0x6e, 0xdc, 0x69, 0xe2, 0xc2, 0x98, 0x06, 0x83, 0x89, 0x0b, 0x77,
	0xe3, 0x70, 0x52, 0x09, 0xa5, 0xd3, 0x74, 0x06, 0x42, 0xdf, 0xc2, 0x17, 0x72, 0xef, 0x92, 0xa5,
	0x4b, 0x03, 0x2f, 0x62, 0x0a, 0xb4, 0xb4, 0x20, 0x0d, 0xee, 0x66, 0x4e, 0x7f, 0xe7, 0xfb, 0xa6,
	0xe7, 0xcb, 0x81, 0xfd, 0x76, 0xd8, 0x43, 0xfa, 0x42, 0x3a, 0x5e, 0x23, 0x3a, 0x39, 0x6c, 0x80,
	0x81, 0x47, 0x3c, 0x8a, 0x0d, 0x31, 0xb4, 0xfc, 0x80, 0x09, 0xa6, 0xa8, 0x09, 0x62, 0x65, 0x11,
	0xa3, 0x05, 0xff, 0x6d, 0xee, 0x3c, 0xa0, 0xb8, 0xc3, 0xf0, 0x91, 0xb8, 0x7d, 0x54, 0x54, 0xf8,
	0x4b, 0x03, 0x24, 0x82, 0x05, 0xaa, 0x54, 0x97, 0xcc, 0x62, 0x2b, 0xbe, 0x2a, 0x15, 0x90, 0xbb,
	0x18, 0xaa, 0xbf, 0xa6, 0xd5, 0xe8, 0xa8, 0x54, 0xe1, 0xf7, 0x20, 0x6a, 0x52, 0xe5, 0x69, 0x6d,
	0x76, 0x31, 0x54, 0xa8, 0x65, 0x35, 0x5b, 0xc8, 0x7d, 0xe6, 0x71, 0x34, 0x4c, 0x28, 0x45, 0x5f,
	0x04, 0xe9, 0x62, 0xf4, 0x8e, 0xf5, 0x5e, 0x46, 0x0d, 0xaa, 0x69, 0x32, 0x51, 0x38, 0x82, 0xb2,
	0xcd, 0x9d, 0x1b, 0x17, 0xa9, 0xb8, 0x6a, 0x0f, 0x3a, 0x9c, 0x05, 0x39, 0x22, 0x3b, 0xb0, 0xbd,
	0x04, 0x27, 0x3a, 0x21, 0x6c, 0xd9, 0xdc, 0x89, 0xaa, 0x14, 0x9b, 0xde, 0x7d, 0xc0, 0x7c, 0xc6,
	0x89, 0x9b, 0xf3, 0xf3, 0x3a, 0x80, 0x3f, 0xa7, 0x6e, 0xdb, 0xf3, 0x19, 0xa4, 0x2a, 0x8a, 0x09,
	0x65, 0x32, 0xf3, 0x08, 0x9b, 0x7d, 0x41, 0x59, 0x2f, 0x1e, 0xca, 0x72, 0xd9, 0xd8, 0x83, 0xdd,
	0x6f, 0xac, 0xe3, 0x97, 0x9d, 0xbd, 0xc9, 0x20, 0xdb, 0xdc, 0x51, 0x3a, 0xf0, 0x2f, 0x1d, 0x8b,
	0x69, 0xad, 0xcb, 0xd0, 0xca, 0x0e, 0x5b, 0x3b, 0xd9, 0x94, 0x8c, 0x2d, 0x15, 0x0a, 0xc5, 0x45,
	0x26, 0x07, 0xf9, 0xed, 0x31, 0xa7, 0x59, 0x9b, 0x71, 0x89, 0x89, 0x0b, 0xa5, 0x4c, 0x6c, 0x87,
	0xb9, 0xfd, 0x69, 0x54, 0x3b, 0xdd, 0x18, 0x4d, 0xdc, 0x86, 0x50, 0x59, 0x09, 0xf7, 0x38, 0x57,
	0x66, 0x19, 0xd7, 0x2e, 0x7e, 0x84, 0xc7, 0xce, 0xd7, 0x97, 0xef, 0x63, 0x5d, 0x1a, 0x8d, 0x75,
	0xe9, 0x73, 0xac, 0x4b, 0xaf, 0x13, 0xbd, 0x30, 0x9a, 0xe8, 0x85, 0x8f, 0x89, 0x5e, 0x78, 0xaa,
	0x2f, 0x16, 0x75, 0xb8, 0xb2, 0xaa, 0xa1, 0x8f, 0xfc, 0xf9, 0xcf, 0x74, 0x5d, 0xcf, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0x81, 0x20, 0x31, 0xd3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetKeyValue(ctx context.Context, in *MsgSetKeyValue, opts ...grpc.CallOption) (*MsgSetKeyValueResponse, error)
	Stakedyme(ctx context.Context, in *MsgStakedyme, opts ...grpc.CallOption) (*MsgStakedymeResponse, error)
	ElectAdvisor(ctx context.Context, in *MsgElectAdvisor, opts ...grpc.CallOption) (*MsgElectAdvisorResponse, error)
	AdviceOnProposal(ctx context.Context, in *MsgAdviceOnProposal, opts ...grpc.CallOption) (*MsgAdviceOnProposalResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetKeyValue(ctx context.Context, in *MsgSetKeyValue, opts ...grpc.CallOption) (*MsgSetKeyValueResponse, error) {
	out := new(MsgSetKeyValueResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Msg/SetKeyValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Stakedyme(ctx context.Context, in *MsgStakedyme, opts ...grpc.CallOption) (*MsgStakedymeResponse, error) {
	out := new(MsgStakedymeResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Msg/Stakedyme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ElectAdvisor(ctx context.Context, in *MsgElectAdvisor, opts ...grpc.CallOption) (*MsgElectAdvisorResponse, error) {
	out := new(MsgElectAdvisorResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Msg/ElectAdvisor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AdviceOnProposal(ctx context.Context, in *MsgAdviceOnProposal, opts ...grpc.CallOption) (*MsgAdviceOnProposalResponse, error) {
	out := new(MsgAdviceOnProposalResponse)
	err := c.cc.Invoke(ctx, "/dymechain.dymegovernance.Msg/AdviceOnProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetKeyValue(context.Context, *MsgSetKeyValue) (*MsgSetKeyValueResponse, error)
	Stakedyme(context.Context, *MsgStakedyme) (*MsgStakedymeResponse, error)
	ElectAdvisor(context.Context, *MsgElectAdvisor) (*MsgElectAdvisorResponse, error)
	AdviceOnProposal(context.Context, *MsgAdviceOnProposal) (*MsgAdviceOnProposalResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetKeyValue(ctx context.Context, req *MsgSetKeyValue) (*MsgSetKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKeyValue not implemented")
}
func (*UnimplementedMsgServer) Stakedyme(ctx context.Context, req *MsgStakedyme) (*MsgStakedymeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stakedyme not implemented")
}
func (*UnimplementedMsgServer) ElectAdvisor(ctx context.Context, req *MsgElectAdvisor) (*MsgElectAdvisorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ElectAdvisor not implemented")
}
func (*UnimplementedMsgServer) AdviceOnProposal(ctx context.Context, req *MsgAdviceOnProposal) (*MsgAdviceOnProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdviceOnProposal not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetKeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Msg/SetKeyValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetKeyValue(ctx, req.(*MsgSetKeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Stakedyme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStakedyme)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Stakedyme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Msg/Stakedyme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Stakedyme(ctx, req.(*MsgStakedyme))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ElectAdvisor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgElectAdvisor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ElectAdvisor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Msg/ElectAdvisor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ElectAdvisor(ctx, req.(*MsgElectAdvisor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AdviceOnProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAdviceOnProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AdviceOnProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymechain.dymegovernance.Msg/AdviceOnProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AdviceOnProposal(ctx, req.(*MsgAdviceOnProposal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dymechain.dymegovernance.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetKeyValue",
			Handler:    _Msg_SetKeyValue_Handler,
		},
		{
			MethodName: "Stakedyme",
			Handler:    _Msg_Stakedyme_Handler,
		},
		{
			MethodName: "ElectAdvisor",
			Handler:    _Msg_ElectAdvisor_Handler,
		},
		{
			MethodName: "AdviceOnProposal",
			Handler:    _Msg_AdviceOnProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dymechain/dymegovernance/tx.proto",
}

func (m *MsgSetKeyValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetKeyValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetKeyValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetKeyValueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetKeyValueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetKeyValueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgStakedyme) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStakedyme) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStakedyme) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStakedymeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStakedymeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStakedymeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgElectAdvisor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgElectAdvisor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgElectAdvisor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgElectAdvisorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgElectAdvisorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgElectAdvisorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAdviceOnProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAdviceOnProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAdviceOnProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AdvisoryOutcome) > 0 {
		i -= len(m.AdvisoryOutcome)
		copy(dAtA[i:], m.AdvisoryOutcome)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AdvisoryOutcome)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProposalId) > 0 {
		i -= len(m.ProposalId)
		copy(dAtA[i:], m.ProposalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ProposalId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAdviceOnProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAdviceOnProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAdviceOnProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetKeyValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetKeyValueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgStakedyme) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStakedymeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgElectAdvisor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgElectAdvisorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAdviceOnProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ProposalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AdvisoryOutcome)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAdviceOnProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetKeyValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetKeyValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetKeyValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetKeyValueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetKeyValueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetKeyValueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStakedyme) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStakedyme: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStakedyme: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStakedymeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStakedymeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStakedymeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgElectAdvisor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgElectAdvisor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgElectAdvisor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgElectAdvisorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgElectAdvisorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgElectAdvisorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAdviceOnProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAdviceOnProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAdviceOnProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvisoryOutcome", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdvisoryOutcome = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAdviceOnProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAdviceOnProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAdviceOnProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)